export enum MicroServiceClient {
  AUTH_CLIENT = 'AUTH_CLIENT',
  ESCROW_CLIENT = 'ESCROW_CLIENT',
  MEDIA_CLIENT = 'MEDIA_CLIENT',
  NOTIFICATION_CLIENT = 'NOTIFICATION_CLIENT',
  PAYMENT_CLIENT = 'PAYMENT_CLIENT',
  PROPERTY_CLIENT = 'PROPERTY_CLIENT',
  USER_CLIENT = 'USER_CLIENT',
}
