export enum MicroServiceClient {
  AUTH_CLIENT = 'AUTH_CLIENT',
  ESCROW_CLIENT = 'ESCROW_CLIENT',
  GATEWAY_CLIENT = 'GATEWAY_CLIENT',
  MEDIA_CLIENT = 'MEDIA_CLIENT',
  NOTIFY_CLIENT = 'NOTIFY_CLIENT',
  ORCHESTRATOR_CLIENT = 'ORCHESTRATOR_CLIENT',
  PAYMENTS_CLIENT = 'PAYMENTS_CLIENT',
  PROPERTIES_CLIENT = 'PROPERTIES_CLIENT',
  USERS_CLIENT = 'USERS_CLIENT',
}
